spring:
  application:
    name: money-transfer-system

  datasource:
    url: jdbc:mysql://localhost:3306/money_transfer_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

